using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProductAPI.Models
{
    /// <summary>
    /// Model for product
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Product ID - generated by database, leave null
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        /// <summary>
        /// Product Name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Product Price, in pounds
        /// </summary>
        public string Price { get; set; }

       
    }
}
